accounts/urls.py
from django.urls import path

from accounts import views

urlpatterns = [
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
    path("register/", views.register_view, name="register"),
]


app_name = "accounts"

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("movies.urls", namespace="movies")),
    path('api/', include("movies.api_urls", namespace="api_movies")),
    path('accounts/', include("accounts.urls", namespace="accounts"))
]

templates/base/nav/_footer.html
<footer class="py-3 my-4 fixed-bottom">
  <ul class="nav justify-content-center border-bottom pb-3 mb-3">
    <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Home</a></li>
    <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Features</a></li>
    <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Pricing</a></li>
    <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">FAQs</a></li>
    <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">About</a></li>
  </ul>
  <p class="text-center text-muted">© 2021 Company, Inc</p>
</footer>

templates/base/nav/_header.html
<header class="p-3 bg-dark text-white">
  <div class="container">
    <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
      <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
        <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap"><use xlink:href="#bootstrap"></use></svg>
      </a>

      <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
        <li><a href="#" class="nav-link px-2 text-secondary">Home</a></li>
        <li><a href="#" class="nav-link px-2 text-white">Features</a></li>
        <li><a href="#" class="nav-link px-2 text-white">Pricing</a></li>
        <li><a href="#" class="nav-link px-2 text-white">FAQs</a></li>
        <li><a href="#" class="nav-link px-2 text-white">About</a></li>
      </ul>

      <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3">
        <input type="search" class="form-control form-control-dark" placeholder="Search..." aria-label="Search">
      </form>

      <div class="text-end">
        {% if user.is_authenticated %}
          <span>{{ user.username }}</span>
          <a href="{% url 'accounts:logout' %}">
            <button type="button" class="btn btn-warning">Logout</button>
          </a>
        {% else %}
          <a href="{% url 'accounts:login' %}">
            <button type="button" class="btn btn-outline-light me-2">Login</button>
          </a>
          <a href="{% url 'accounts:register' %}">
            <button type="button" class="btn btn-warning">Sign-up</button>
          </a>
        {% endif %}
      </div>
    </div>
  </div>
</header>