config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("movies.urls", namespace="movies")),
    path('api/', include("movies.api_urls", namespace="api_movies")),
    path('accounts/', include("accounts.urls", namespace="accounts"))
]

movies/urls.py
from django.urls import path

from movies.views import movie_list_view, MovieListView

urlpatterns = [
    # path('', movie_list_view, name="movie_list"),
    path('', MovieListView.as_view(), name='movie_list')
]

app_name = "movies"

movies/models.py
from django.db import models


class Genre(models.Model):
    name = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ('name',)


class Certification(models.Model):
    name = models.CharField(max_length=10, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ('name',)


class Director(models.Model):
    name = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ('name',)


class Star(models.Model):
    name = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ('name',)


class Movie(models.Model):
    name = models.CharField(max_length=250)
    year = models.IntegerField()
    time = models.IntegerField()
    imdb = models.FloatField()
    votes = models.IntegerField()
    meta_score = models.FloatField(null=True)
    gross = models.FloatField(null=True)
    certification = models.ForeignKey(Certification, on_delete=models.PROTECT, related_name='movies')
    description = models.TextField()

    def __str__(self):
        return f"{self.name} ({self.year})"

    class Meta:
        ordering = ('name', 'year')


class MovieGenre(models.Model):
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE, related_name='movie_genres')
    genre = models.ForeignKey(Genre, on_delete=models.CASCADE, related_name='genre_movies')

    def __str__(self):
        return f"{self.movie} - {self.genre}"

    class Meta:
        unique_together = ('movie', 'genre')


class MovieDirector(models.Model):
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE, related_name='movie_directors')
    director = models.ForeignKey(Director, on_delete=models.CASCADE, related_name='director_movies')

    def __str__(self):
        return f"{self.movie} - {self.director}"

    class Meta:
        unique_together = ('movie', 'director')


class MovieStar(models.Model):
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE, related_name='movie_stars')
    star = models.ForeignKey(Star, on_delete=models.CASCADE, related_name='star_movies')

    def __str__(self):
        return f"{self.movie} - {self.star}"

    class Meta:
        unique_together = ('movie', 'star')

movies/views.py
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render
from django.views.generic import ListView
from rest_framework import viewsets

from movies.models import Movie
from movies.serializers import MovieSerializer


def movie_list_view(request: HttpRequest) -> HttpResponse:
    movies = Movie.objects.all()[:5]
    context = {
        "movies": movies,
    }
    return render(request, "movies/movies_list.html", context=context)


class MovieListView(ListView):
    model = Movie
    template_name = "movies/movies_list.html"
    context_object_name = "movies"
    paginate_by = 4

    def get_queryset(self):
        genre_filter = self.request.GET.get("genre")

        queryset = super().get_queryset()

        if genre_filter:
            queryset = queryset.filter(movie_genres__genre__name=genre_filter)

        return queryset
class MoviesViewSet(viewsets.ModelViewSet):
    queryset = Movie.objects.all()[:5]
    serializer_class = MovieSerializer

templates/movies/movies_list.html
{% extends 'base/_base.html' %}

{% block title %}
  Movies list

{% endblock %}

{% block content %}
  <div class="row mb-2">
  {% for movie in movies %}
    <div class="col-md-6">
      <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
        <div class="col p-4 d-flex flex-column position-static">
          <strong class="d-inline-block mb-2 text-primary">
            {% for movie_genre in movie.movie_genres.all %}
              {{ movie_genre.genre }},
            {% endfor %}
          </strong>
          <h3 class="mb-0">{{ movie.name }}</h3>
          <div class="mb-1 text-muted">Nov 12</div>
          <p class="card-text mb-auto">{{ movie.description }}</p>
          <a href="{% url 'movies:movie_list' %}" class="stretched-link">Continue reading</a>
        </div>
        <div class="col-auto d-none d-lg-block">
          <svg class="bd-placeholder-img" width="200" height="250" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"></rect><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg>
        </div>
      </div>
    </div>
  {% endfor %}
  </div>

  <hr>
  <nav aria-label="Page navigation example">
    <ul class="pagination justify-content-center">
      <li class="page-item {% if not page_obj.has_previous %} disabled {% endif %}">
        <a class="page-link" href="?page={% if page_obj.has_previous %} {{ page_obj.previous_page_number }} {% else %}# {% endif %}" tabindex="-1" aria-disabled="true">Previous</a>
      </li>
      {% if page_obj.has_previous %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
        </li>
      {% endif %}
      <li class="page-item disabled"><a class="page-link" href="#">{{ page_obj.number }}</a></li>

    {% if page_obj.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}">
          {{ page_obj.next_page_number }}
        </a>
      </li>
    {% endif %}

      <li class="page-item {% if not page_obj.has_next %}disabled{% endif %}">
        <a class="page-link" href="?page={% if page_obj.has_next%}{{ page_obj.next_page_number }}{% else %}#{% endif %}">Next</a>
      </li>

    </ul>
    <p>Total pages: {{ paginator.num_pages }}</p>
  </nav>
{% endblock %}